### PR TITLE
Update pydantic pin

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
Resolves #31

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
I'm not sure when this was switch from a warning to a error:
```
2023-07-14T19:06:45.7626957Z     def check_dict_or_set_indexers(key) -> None:
2023-07-14T19:06:45.7627176Z         """
2023-07-14T19:06:45.7627406Z         Check if the indexer is or contains a dict or set, which is no longer allowed.
2023-07-14T19:06:45.7627642Z         """
2023-07-14T19:06:45.7627822Z         if (
2023-07-14T19:06:45.7628029Z             isinstance(key, set)
2023-07-14T19:06:45.7628250Z             or isinstance(key, tuple)
2023-07-14T19:06:45.7628485Z             and any(isinstance(x, set) for x in key)
2023-07-14T19:06:45.7628704Z         ):
2023-07-14T19:06:45.7628896Z >           raise TypeError(
2023-07-14T19:06:45.7629137Z                 "Passing a set as an indexer is not supported. Use a list instead."
2023-07-14T19:06:45.7629420Z             )
2023-07-14T19:06:45.7629664Z E           TypeError: Passing a set as an indexer is not supported. Use a list instead.
```

But it is coming from pandas. Skimming the change log, I think I found where the switch happened, but I could be wrong.

**Comment by bennybp** [comment]
@conda-forge-admin, please rerender

**Comment by bennybp** [comment]
Sorry for the delay. This looks reasonable to me.

For the `next` release, we are decommissioning/archiving this feedstock in favor of building all packages in the qcfractal-feedstock. But hopefully this build will stick around for a while.

**Pull request merged**
